linters:
  enable:
    - gofmt
    - revive        # замена устаревшего golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - shadow       # явно включаем проверку shadowing

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
  revive:
    min-confidence: 0.8